
# Reader name
name: "ship-reader-1"

# Endpoint to nodeos api
api: "http://192.168.1.74:8888"
message_codec: "json"

# Logging settings
log:
  # Filename to use.
  filename: thalos
  # Directory to store the logfiles in.
  directory: logs
  # Format to rename log files when rotating
  time_format: 2006-01-02_150405

  # Log rotation, logfile is rotated when any of these
  # conditions are met. set to 0 or remove to disable.

  # Rotate when the file reaches this size.
  max_filesize: 200mb
  # Rotate when the file is this old.
  max_time: 24h

# SHIP settings
ship:

  # Url to ship api.
  url: "ws://192.168.1.74:8080"

  # Name of chain. Note that this is just a name to be used in channel namespace.
  # If unset, chain id from api is used.
  # chain: wax

  # Fetch irreversible blocks only
  # irreversible_only: true

  # Request ship to start sending blocks from this block.
  # If not set, the head block reported by the nodeos api is used.
  #start_block_num: 1000

  # Request ship to stop sending blocks when reaching this block.
  #end_block_num: 2000

# Telegram notifications
#telegram:
#  id: "123456789:GPdmGPBWvpgHPxlergJLavus-PoAURTjMWP"
#  channel: -123456789

# Redis settings
redis:
  # Address (and port) to redis server
  addr: "redis:6379"

  # Username to use when authenticating
  user: ""

  # Password to use when authenticating
  pasword: ""

  # database index
  db: 0

  # Key prefix.
  prefix: "ship"
